title: MC Serigrafia
description: Impressos do futuro, entregues hoje
baseurl: "/MEU-SITE-MC"  # Nome do seu repositório
url: "https://marciliorsflores.github.io"
collections:
  itens:
    output: true
