backend:
  name: github
  repo: marciliorsflores/MEU-SITE-MC
  branch: main
media_folder: "imagens"
public_folder: "/imagens"
collections:
  - name: "itens"
    label: "Itens"
    folder: "_itens"
    create: true
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Imagem", name: "image", widget: "image" }
      - { label: "Preço", name: "price", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
